### PR TITLE
Add item-item thresholding

### PR DESCRIPTION
**Pull request by mdekstrand**
This makes several item-item improvements:

- More and better logging
- Factor out progress estimation to use consistent logic across the system
- Add `@MinCommonUsers` thresholding (#843)

### CODE REVIEW

**Comment by mdekstrand** [comment]
When this is merged, we need to open a ticket to add smoothing to the progress estimation.

**Comment by mdekstrand** [comment]
Just added several more updates to this from my backlog, along with some item-item performance improvements.

I don't intend this `VectorTransformation` change to be our long-term direction — vector normalization is going to be retooled for LK3 — but it lets us get some immediate perf boost.

**Comment by christklimkiewicz** [comment]
Please take me off this mail list

Christopher Klimkiewicz

**Comment by mdekstrand** [comment]
@christklimkiewicz This message was delivered by GitHub Notifications; you will need to unsubscribe through GitHub (try unwatching the LensKit repository).

**Pull request merged**
